site_name: The Onet Content Store
theme:
  name: material
  palette:
    scheme: preference
  font: false
repo_url: https://github.com/onet-team/onet
repo_name: onet-team/onet
plugins:
  - git-revision-date-localized
markdown_extensions:
  - def_list
