site_name: The Onet Content Store
theme:
  name: material
  palette:
    scheme: preference
  font: false
repo_url: https://github.com/onet-team/onet
site_url: https://onet-team.github.io/onet/
repo_name: onet-team/onet
plugins:
  - git-revision-date-localized
markdown_extensions:
  - def_list


nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started.md
    - Clients: concepts/clients.md
    - Servers: concepts/servers.md
    - Viewers: concepts/viewers.md
  - Command Line: command-line.md
  - Concepts:
    - Overview: concepts/overview.md
    - Spaces: concepts/spaces.md
    - Transactions: concepts/transactions.md
  - Repository:
    - Overview: repository/overview.md
    - Layout: repository/layout.md
    - Stores: 
      - Overview: repository/stores-overview.md
      - HiStore: repository/histore.md
      - Chunked Store: repository/chunked-store.md
      - UUID Store: repository/uuid-store.md

